# Generated by Django 4.2.25 on 2025-10-08 00:26

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_category_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='auction',
            name='end_date',
            field=models.DateTimeField(validators=[django.core.validators.MinValueValidator(django.utils.timezone.now, message='End date must be in the future.')]),
        ),
        migrations.AlterField(
            model_name='auction',
            name='entry_fee',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0, message='Entry fee cannot be negative.')]),
        ),
        migrations.AlterField(
            model_name='item',
            name='min_increment',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01, message='Minimum increment must be a positive amount.')]),
        ),
        migrations.AlterField(
            model_name='item',
            name='start_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0, message='Start price cannot be negative.')]),
        ),
    ]
