# Generated by Django 4.2.25 on 2025-10-08 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
    ]
