<<<<<<< HEAD
# Generated by Django 4.2.25 on 2025-10-08 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auction_slug'),
    ]

    operations = [
        migrations.AlterModelTableComment(
            name='item',
            table_comment='Auction Items',
        ),
        migrations.AlterField(
            model_name='auction',
            name='status',
            field=models.CharField(blank=True, choices=[('draft', 'Draft'), ('active', 'Active'), ('closed', 'Closed')], default='draft', max_length=255, null=True),
        ),
    ]
=======
# Generated by Django 4.2.25 on 2025-10-08 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auction_slug'),
    ]

    operations = [
        migrations.AlterModelTableComment(
            name='item',
            table_comment='Auction Items',
        ),
        migrations.AlterField(
            model_name='auction',
            name='status',
            field=models.CharField(blank=True, choices=[('draft', 'Draft'), ('active', 'Active'), ('closed', 'Closed')], default='draft', max_length=255, null=True),
        ),
    ]
>>>>>>> origin/master
