# Generated by Django 4.2.25 on 2025-10-08 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_item_table_comment_alter_auction_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='status',
        ),
    ]
