# Generated by Django 4.2.25 on 2025-10-17 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_auction_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='reserve_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='bid',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='main.item'),
        ),
    ]
