# Generated by Django 4.2.25 on 2025-10-17 13:25

from django.db import migrations
import main.custom_fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_item_created_at_item_is_active_item_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='location',
            field=main.custom_fields.LocationField(blank=True, default={'city': '', 'country': '', 'latitude': '', 'longitude': '', 'state': ''}, null=True),
        ),
    ]
