<<<<<<< HEAD
# Generated by Django 4.2.25 on 2025-10-17 13:27

from django.db import migrations
import main.custom_fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_item_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='location',
            field=main.custom_fields.LocationField(blank=True, default=main.custom_fields.default_location, null=True),
        ),
    ]
=======
# Generated by Django 4.2.25 on 2025-10-17 13:27

from django.db import migrations
import main.custom_fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_item_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='location',
            field=main.custom_fields.LocationField(blank=True, default=main.custom_fields.default_location, null=True),
        ),
    ]
>>>>>>> d41bd5c2f71c127f5bc5d5e18d3eed1ed818de8e
