# Generated by Django 4.2.25 on 2025-10-17 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_item_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='end_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
