# Generated by Django 4.2.25 on 2025-11-30 21:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('ROOM_JOINED', 'Joined Bidding Room'), ('ROOM_LEFT', 'Left Bidding Room'), ('AUCTION_CREATED', 'Auction Has Been Created'), ('OUTBID', 'You have been outbid'), ('AUCTION_WON', 'Auction Won'), ('SYSTEM_UPDATE', 'System Maintenance')], max_length=50)),
                ('object_id', models.PositiveIntegerField(blank=True, help_text='The primary key of the related object.', null=True)),
                ('content', models.CharField(blank=True, help_text='The pre-rendered notification message.', max_length=255, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(blank=True, help_text="The type of the related object (e.g., 'Auction', 'Bid').", null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications_sent', to=settings.AUTH_USER_MODEL, verbose_name='Sender (Causer)')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications_received', to=settings.AUTH_USER_MODEL, verbose_name='Recipient')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
